#!/usr/bin/env python3
"""Generate src/stdlib/_ucd.py, the data of minipy's unicodedata module, from this
Python's unicodedata (the module and the data then agree with it on every code point).

The tables are strings of numbers, each a little-endian varint of 6-bit characters
(five bits of the number, the sixth: more follow), so the module source stays ASCII
and small; unicodedata.py decodes a table the first time a function needs it.

usage: python3 tools/gen_unicodedata.py      (rewrites src/stdlib/_ucd.py)
"""
import os
import unicodedata as U

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "src", "stdlib", "_ucd.py")
ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
# names a code point's own number makes (the hex digits after the prefix)
ALGORITHMIC = ["CJK UNIFIED IDEOGRAPH-", "CJK COMPATIBILITY IDEOGRAPH-", "TANGUT IDEOGRAPH-",
               "KHITAN SMALL SCRIPT CHARACTER-", "NUSHU CHARACTER-", "EGYPTIAN HIEROGLYPH-"]


def enc(nums):
    out = []
    for n in nums:
        assert n >= 0, n
        while n >= 32:
            out.append(ALPHABET[(n & 31) | 32])
            n >>= 5
        out.append(ALPHABET[n])
    return "".join(out)


def chunked(name, s, width=100):
    lines = ["%s = (" % name]
    for i in range(0, len(s), width):
        lines.append("    %r" % s[i:i + width])
    if not s:
        lines.append("    ''")
    lines.append(")")
    return "\n".join(lines)


def main():
    cats, bidis, eaws, nums = [], [], [], []

    def idx(lst, v):
        if v not in lst:
            lst.append(v)
        return lst.index(v)

    # ---- per code point properties: runs of one record
    records, rec_index, runs = [], {}, []
    prev = None
    for c in range(0x110000):
        ch = chr(c)
        num = U.numeric(ch, None)
        r = (idx(cats, U.category(ch)), idx(bidis, U.bidirectional(ch)), U.combining(ch), U.mirrored(ch),
             idx(eaws, U.east_asian_width(ch)),
             0 if U.decimal(ch, None) is None else U.decimal(ch) + 1,
             0 if U.digit(ch, None) is None else U.digit(ch) + 1,
             0 if num is None else idx(nums, repr(num)) + 1)
        if r not in rec_index:
            rec_index[r] = len(records)
            records.append(r)
        if r != prev:
            runs.append((c, rec_index[r]))
            prev = r
    run_nums, last = [], 0
    for c, ri in runs:
        run_nums += [c - last, ri]
        last = c
    rec_nums = [x for r in records for x in r]

    # ---- decompositions (Hangul syllables: by their algorithm)
    tags = [""]
    dec_nums, last = [], 0
    comp_excl = []
    for c in range(0x110000):
        if 0xAC00 <= c <= 0xD7A3:
            continue
        d = U.decomposition(chr(c))
        if not d:
            continue
        parts = d.split()
        tag = ""
        if parts[0].startswith("<"):
            tag = parts.pop(0)
        cps = [int(p, 16) for p in parts]
        dec_nums += [c - last, idx(tags, tag), len(cps)] + cps
        last = c
        if not tag and len(cps) == 2 and U.normalize("NFC", chr(c)) != chr(c):
            comp_excl.append(c)
    excl_nums, last = [], 0
    for c in comp_excl:
        excl_nums.append(c - last)
        last = c

    # ---- names: words by frequency; each name its word numbers (+1), then 0
    named = []
    algo = []                       # (prefix, first, last)
    for c in range(0x110000):
        n = U.name(chr(c), None)
        if n is None or 0xAC00 <= c <= 0xD7A3:
            continue
        pre = next((p for p in ALGORITHMIC if n.startswith(p) and n == p + "%04X" % c), None)
        if pre is not None:
            if algo and algo[-1][0] == pre and algo[-1][2] == c - 1:
                algo[-1] = (pre, algo[-1][1], c)
            else:
                algo.append((pre, c, c))
            continue
        named.append((c, n))
    freq = {}
    for c, n in named:
        for w in n.split(" "):
            freq[w] = freq.get(w, 0) + 1
    words = sorted(freq, key=lambda w: (-freq[w], w))
    wid = {w: i + 1 for i, w in enumerate(words)}
    cp_nums, name_nums, block_nums, last = [], [], [], 0
    text_len = 0
    for i, (c, n) in enumerate(named):
        if i % 32 == 0:
            block_nums.append(len(enc(name_nums)) if False else text_len)
        cp_nums.append(c - last)
        last = c
        ids = [wid[w] for w in n.split(" ")] + [0]
        name_nums += ids
        text_len += len(enc(ids))

    parts = ['"""The Unicode %s character database of minipy\'s unicodedata module.' % U.unidata_version,
             "", "Generated by tools/gen_unicodedata.py from Python's unicodedata: do not edit.", '"""', "",
             "UNIDATA_VERSION = %r" % U.unidata_version,
             "CATEGORIES = %r" % " ".join(cats),
             "BIDIRECTIONAL = %r" % " ".join(bidis),
             "EAST_ASIAN_WIDTHS = %r" % " ".join(eaws),
             "NUMERICS = %r" % " ".join(nums),
             "DECOMPOSITION_TAGS = %r" % " ".join(tags),
             "ALGORITHMIC_NAMES = %r" % [(p, a, b) for p, a, b in algo],
             chunked("RUNS", enc(run_nums)),
             chunked("RECORDS", enc(rec_nums)),
             chunked("DECOMPOSITIONS", enc(dec_nums)),
             chunked("COMPOSITION_EXCLUSIONS", enc(excl_nums)),
             chunked("WORDS", " ".join(words)),
             chunked("NAME_CODES", enc(cp_nums)),
             chunked("NAME_BLOCKS", enc(block_nums)),
             chunked("NAMES", enc(name_nums)), ""]
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    print("wrote %s: %d runs, %d records, %d names, %d words, %d bytes"
          % (OUT, len(runs), len(records), len(named), len(words), os.path.getsize(OUT)))


main()
