#!/usr/bin/env python3
"""Generate minipy's Unicode character data from this Python's unicodedata.

One description of the code points feeds both the interpreter
(src/i_unicode.h) and compiled programs (the rt_unicode, rt_noprint and
rt_ucspecial blocks of src/aot_rtlib.asm), so the two agree on every
character. Covered as CPython sees them: everything below U+0700 (Latin,
IPA, Greek, Cyrillic, Armenian, Hebrew, Arabic), general punctuation, number
forms, CJK symbols and kana, CJK ideographs, Hangul, fullwidth forms;
other code points have no class or case. Which code points are printable
(repr, str.isprintable) is known for all of Unicode.

usage: python3 tools/gen_unicode.py      (rewrites both files in place)
"""
import os
import re
import sys
import unicodedata

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOCKS = [(0, 0x6FF), (0x1680, 0x1680), (0x2000, 0x206F), (0x2150, 0x218F), (0x3000, 0x30FF),
          (0x4E00, 0x9FFF), (0xAC00, 0xD7A3), (0xFF00, 0xFF65)]
# non-printable code points are looked up separately (repr needs them alone): all of Unicode
NOPRINT_BLOCKS = [(0, 0x10FFFF)]
# Case_Ignorable beyond the categories Mn Me Cf Lm Sk (Word_Break MidLetter, MidNumLet, Single_Quote)
IGNORABLE = {0x27, 0x2E, 0x3A, 0xB7, 0x387, 0x55F, 0x5F4, 0x2018, 0x2019, 0x2024, 0x2027,
             0xFE13, 0xFE52, 0xFE55, 0xFF07, 0xFF0E, 0xFF1A}
ALPHA, DIGIT, DECIMAL, NUMERIC, SPACE, UPPER, LOWER, CASED, IGNOR, TITLE = 1, 2, 4, 8, 16, 32, 64, 128, 512, 1024


def props(c):
    ch = chr(c)
    cat = unicodedata.category(ch)
    up, lo, ti = ch.isupper(), ch.islower(), cat == 'Lt'
    bits = (ALPHA * ch.isalpha() | DIGIT * ch.isdigit() | DECIMAL * ch.isdecimal() | NUMERIC * ch.isnumeric()
            | SPACE * ch.isspace() | UPPER * up | LOWER * lo | CASED * (up or lo or ti) | TITLE * ti
            | IGNOR * (cat in ('Mn', 'Me', 'Cf', 'Lm', 'Sk') or c in IGNORABLE))
    u, l = ch.upper(), ch.lower()
    # deltas modulo 0x10000: every mapping in the covered blocks stays in the BMP
    return (bits, (ord(u) - c) & 0xFFFF if len(u) == 1 else 0, (ord(l) - c) & 0xFFFF if len(l) == 1 else 0)


def ranges():
    """sorted (lo, hi, props at an even distance from lo, props at an odd one)"""
    out = []
    for lo, hi in BLOCKS:
        c = lo
        while c <= hi:
            p = props(c)
            if p == (0, 0, 0):
                c += 1
                continue
            h, q = c, p
            if c + 1 <= hi and props(c + 1) == p:
                while h + 1 <= hi and props(h + 1) == p:
                    h += 1
            elif c + 3 <= hi and props(c + 2) == p and props(c + 3) == props(c + 1) and p != props(c + 1):
                q, h = props(c + 1), c + 1
                while h + 1 <= hi and props(h + 1) == props(h - 1):
                    h += 1
            out.append((c, h, p, q))
            c = h + 1
    return out


def noprint():
    out = []
    for lo, hi in sorted(NOPRINT_BLOCKS):            # (in order: the tables are searched by halves)
        for c in range(max(lo, 0x80), hi + 1):
            if not chr(c).isprintable():
                if out and out[-1][1] == c - 1:
                    out[-1][1] = c
                else:
                    out.append([c, c])
    return out


def specials():
    """mappings that are not one code point to one: (cp, kind, text); kind U upper, L lower, T title, F casefold"""
    out = []
    for lo, hi in BLOCKS:
        for c in range(lo, hi + 1):
            ch = chr(c)
            u, l, t, f = ch.upper(), ch.lower(), ch.title(), ch.casefold()
            if len(u) != 1:
                out.append((c, 'U', u))
            if len(l) != 1:
                out.append((c, 'L', l))
            if t != u:
                out.append((c, 'T', t))
            if f != l:
                out.append((c, 'F', f))
    return out


def c_text(s):
    return '"' + ''.join('\\x%02x' % b for b in s.encode()) + '"'


def asm_bytes(s):
    return ','.join(str(b) for b in s.encode()) + ',0'


def main():
    R, N, S = ranges(), noprint(), specials()
    ver = '%d.%d' % sys.version_info[:2]
    h = ['/* Generated by tools/gen_unicode.py from Python %s\'s unicodedata: do not edit.' % ver,
         '   The same data is in src/aot_rtlib.asm (rt_unicode, rt_noprint, rt_ucspecial). */',
         '#define UC_ALPHA 1', '#define UC_DIGIT 2', '#define UC_DECIMAL 4', '#define UC_NUMERIC 8', '#define UC_SPACE 16',
         '#define UC_UPPER 32', '#define UC_LOWER 64', '#define UC_CASED 128', '#define UC_IGNORABLE 512', '#define UC_TITLE 1024',
         '/* lo, hi; class bits, upper - cp, lower - cp (mod 0x10000) at an even distance from lo, then at an odd one */',
         'typedef struct { uint32_t lo, hi; uint16_t p[6]; } UcRange;',
         'static const UcRange uc_ranges[%d] = {' % len(R)]
    h += ['    {0x%X,0x%X,{%d,%d,%d,%d,%d,%d}},' % (lo, hi, *p, *q) for lo, hi, p, q in R]
    h += ['};', '/* code points from 0x80 on that repr() escapes */',
          'static const uint32_t uc_noprint[%d][2] = {' % len(N)]
    h += ['    {0x%X,0x%X},' % (lo, hi) for lo, hi in N]
    h += ['};', '/* U upper, L lower, T title, F casefold: when not just one code point (title: unlike upper) */',
          'typedef struct { uint32_t cp; char kind; const char *to; } UcSpecial;',
          'static const UcSpecial uc_special[%d] = {' % len(S)]
    h += ["    {0x%X,'%s',%s}," % (c, k, c_text(t)) for c, k, t in S]
    h += ['};', '']
    with open(os.path.join(ROOT, 'src', 'i_unicode.h'), 'w') as f:
        f.write('\n'.join(h))

    a = [';;; data rt_unicode',
         '; Code point classes and case mappings: tools/gen_unicode.py (src/i_unicode.h has',
         '; the same). Sorted ranges lo, hi, then for the code points at an even and at an',
         '; odd distance from lo: class bits, upper - cp, lower - cp (mod 0x10000). Bits: 1 alpha, 2 digit,',
         '; 4 decimal, 8 numeric, 16 space, 32 upper, 64 lower, 128 cased, 512 case-ignorable,',
         '; 1024 title. Code points in no range: none of them.',
         'align 4',
         'rt_unicode_n    dd %d' % len(R),
         'rt_unicode:']
    for lo, hi, p, q in R:
        a.append('        dd 0x%X,0x%X' % (lo, hi))
        a.append('        dw %d,%d,%d,%d,%d,%d' % (*p, *q))
    a += ['', ';;; data rt_noprint', '; the code points from 0x80 on that repr() escapes: sorted ranges lo, hi',
          'align 4', 'rt_noprint_n    dd %d' % len(N), 'rt_noprint:']
    for lo, hi in N:
        a.append('        dd 0x%X,0x%X' % (lo, hi))
    a += ['', ';;; data rt_ucspecial',
          '; mappings that are not one code point to one: code point, kind (U upper, L lower,',
          '; T title: unlike upper, F casefold), then the text (UTF-8, NUL-terminated)',
          'rt_ucspecial:']
    for c, k, t in S:
        a.append("        dd 0x%X\n        db '%s',%s" % (c, k, asm_bytes(t)))
    a += ['        dd 0', '']
    p = os.path.join(ROOT, 'src', 'aot_rtlib.asm')
    src = open(p).read()
    start = src.index(';;; data rt_unicode\n')
    end = src.index(';;; code rt_cp_props')
    src = src[:start] + '\n'.join(a) + '\n' + src[end:]
    open(p, 'w').write(src)
    print('%d ranges, %d non-printable ranges, %d special mappings' % (len(R), len(N), len(S)))


if __name__ == '__main__':
    main()
